defaultPortal: alg-sandbox
portals:
  - name: alg-sandbox
    portalId: 24104252
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNGKt7ToMBILAA0AAAAA4A0DQAIYvJq_CyDK5ucXKO7pDDIUE8cELWSd0Z74hhED3gb50vtjRl86NwAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAABgBEAGAAAAAAAAAAAAAAAAAAMAJCFOk6hq44vMfwJF2mWdk_0oLTfY1aSgNuYTFSAFoA
        expiresAt: '2023-02-25T03:11:23.474Z'
    personalAccessKey: >-
      CiQ5YTQ1Nzk2My02YjE5LTRhZjQtOWU1OC1jNGZhMmM1YTEzMzMQvJq_CxjK5ucXKhkABeaRgt2jj71j8TOBjgEvIOhXsZocdMXfSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
